config/routes.rb
Rails.application.routes.draw do
  resources :likes
  resources :posts do 
    resources :likes
  end
  # get "/posts/newsfeed", to: "post#newsfeed", as: "/newsfeed"
  # post "posts/new", to: "post#newsfeed"
  resources :activities
  resources :trips
  resources :countries
  resources :flights
  resources :users
  get "/login", to: "sessions#new"
  post "/login", to: "sessions#create"
  get "/logout", to: "sessions#logout"
  get '/home', to: "welcome#index", as: :home
  root :to => "welcome#index"
  
  

end

app/models/user.rb
class User < ApplicationRecord


    has_many :trips
    has_many :countries, through: :trips
    has_many :posts
    has_many :likes
    has_many :likes, dependent: :destroy
    accepts_nested_attributes_for :trips
    validates :name, presence: true
    validates :username, presence: true, uniqueness: true
    validates :password, 
        presence: true
    #     length: { in: (8..25) }, 
    #     format: { with: PASSWORD_FORMAT }, 
    #     confirmation: true, 
    #     on: :create 
    # validates :password, 
    #     allow_nil: true, 
    #     length: { in: (8..25)}, 
    #     format: { with: PASSWORD_FORMAT }, 
    #     confirmation: true, 
    #     on: :update
          has_secure_password

    def user_past_trips
        self.trips.uniq.sort_by{|trip| trip.start_date}.each do |trip|
            if trip.end_date > Date.today 
                trip
            end
        end
    end

    def user_future_trips
        self.trips.uniq.sort_by{|trip| trip.start_date}.each do |trip|
            if trip.end_date < Date.today 
                trip
            end
        end
    end

    def user_trip_countries
        self.trips.each do |trip|
            trip.flights.each do |flight|
                Country.find_by(id:flight.country_id)
            end
        end
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  helper_method :current_username
  helper_method :current_user
  before_action :find_user, only: [:show, :edit, :update]
  before_action :authorized, except: [:new, :create, :index]
  









  
  def index
    @users = User.all.order('name ASC')
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
      if @user.valid? 
        @user.save
        session[:user_id] = @user.id
        redirect_to user_path(current_user)
      else 
        render :new
    end
  end

  def show
    @user = User.find(params[:id])
    if @user.id != current_user.id
      redirect_to user_path(current_user)
    end
  end

  def edit
  end

  def update
    @user.update(user_params)
    if @user.valid?
    @user.save
    redirect_to user_path(@user.id)
    else
      render :edit
    end
  end

  def destroy
    @user = User.destroy(params[:id])
    redirect_to home_path
  end


  private

  def user_params
    params.require(:user).permit(:id, :name, :passport_number, :username,
      :password, :password_confirmation, trip_ids: [], trips_attributes:[ :name, :start_date, :end_date])
  end

  def find_user
    @user = User.find(params[:id])
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_user_form.html.erb
<div class="container">
<div>
<% if @user.errors.any? %>
    <ul>
    <% @user.errors.full_messages.each do |e| %>
        <li class="error"><%= e %></li>
    <% end %>
    </ul>
<% end %>
</div>
<%= form_for @user do |f| %>
 <div class="form-group">
 <%= f.label :name, class: "form-text"%><br>
 <%= f.text_field :name, class:"form-control", placeholder: "Name" %>
 </div>
 <div class="form-group">
 <%= f.label :passport_number, class: "form-text"%><br>
 <%= f.number_field :passport_number, class:"form-control", placeholder: "Passport Number" %>
 </div>
 <div class="form-group">
 <%= f.label :username, class: "form-text"%><br>
 <%= f.text_field :username, class:"form-control", placeholder: "Username"%>
 </div>
 <div class="form-group">
 <%= f.label :password, class: "form-text"%><br>
 <%= f.password_field :password, class:"form-control", placeholder: "Password" %>
 <%= f.label "Password must contain 8 or more characters, a number, a lower case character, an upper case character & a symbol.", class: "form-text"%><br>
 </div>
 <div class="form-group">
 <%=f.label :password_confirmation, class: "form-text" %>
 <%=f.password_field :password_confirmation, class:"form-control", placeholder: "Password"%>
 </div>
 <div class="form-group">
 <%= token_tag %> 
 <%= f.submit "Submit", class: "btn btn-primary" %>
 <%end %>
 </div>

app/views/users/edit.html.erb
<h1>Edit User</h1>

<%= render partial: 'user_form', locals: {:user => @user} %>

app/views/users/index.html.erb
<h3 style="font-family: 'Permanent Marker', cursive; text-align: center;">All users:</h3>
<%arr = []%>
<%100.times do%>
<%arr << "https://randomuser.me/api/portraits/men/#{rand(1...99)}.jpg"%>
<%arr << "https://randomuser.me/api/portraits/women/#{rand(1...99)}.jpg"%>
<%end%>
<%#  %>


<div class="card-deck">
  <div class="card-columns">
    <% @users.each do |user| %>
    <div class="card ml-5 border-dark mr-3 mb-3 mt-0 ml-0" style="width: 18rem;">
    <img class="card-img-top" style="height: 100px; width: 150px;" src="<%=arr.sample%>" alt="Card image cap">
  <div class="card-body"><%=user.id%>
    <h5 class="card-title"><%= link_to user.name, user_path(user), class: "text-secondary"%></h5>
      <p class="card-text text-black">Number of Posts <%= user.posts.count%></p>
      <p class="card-text text-black">Number of Post likes <%= user.likes.count%></p>
      <p class="card-text text-black">Number of Trips <%= user.trips.count%></p>
    <a href="users/<%=user.id%>" class="btn btn-primary">See Their Page</a>
  </div>
</div>
 <%end%> 

app/views/users/new.html.erb
<h1>Create a new user</h1>


<%= render partial: 'user_form', locals: {:user => @user} %>

app/views/users/show.html.erb
<br>
<h1 class="text-center" style="font-family: 'Permanent Marker', cursive;"><u><%=current_user.name.titleize%>'s Travel Page</u></h1>

<br>
<br>

<h2 class="text-center" style="font-family: 'Permanent Marker', cursive;"> Upcoming Trips </h2>
&nbsp&nbsp
<div class="card-deck justify-content-md-center">
<%current_user.trips.each do |trip|%>
<%if trip.end_date > Date.today%>
<div class="row">
<div class="card bg-light mb-3" style="max-width: 18rem;">
      <h4 class="card-header" style="font-family: 'Permanent Marker', cursive;"><%= link_to trip.name.titleize, trip_path(trip) , class: "text-secondary"  %></h4>
      <div class="card-body">
      <p class="card-text">Trip start date: <%=trip.start_date%></p>
      <p class="card-text">Trip end date: <%=trip.end_date%>.</p>
      </div>
      <br>
</div>
&nbsp&nbsp&nbsp&nbsp&nbsp
</div>
<% end %>
<% end %>
</div>

<br>
<br>

<h2 class="text-center" style="font-family: 'Permanent Marker', cursive;"> Past trips </h2>
&nbsp&nbsp
<div class="card-deck justify-content-md-center">
<%current_user.trips.each do |trip|%>
      <%if trip.end_date < Date.today%>
      <div class="row">
      <div class="card bg-light mb-3" style="max-width: 18rem;">
            <h4 class="card-header" style="font-family: 'Permanent Marker', cursive;"><%= link_to trip.name.titleize, trip_path(trip), class: "text-secondary" %></h4>
            <div class="card-body">
            <p class="card-text">Trip start date: <%=trip.start_date%></p>
            <p class="card-text">Trip end date: <%=trip.end_date%>.</p>
            </div>
      </div>
      &nbsp&nbsp&nbsp&nbsp&nbsp
      </div>
      <% end %>
      <% end %>
      </div>

<br>
<br>
      
  <h2 class="text-center" style="font-family: 'Permanent Marker', cursive;">Countries Visited</h2>
  &nbsp&nbsp
  <div class="card-deck justify-content-md-center">
  <%if current_user.user_trip_countries != [] %>
  <%current_user.countries.uniq.each do |country|%>
  <div class="row">
  <div class="card bg-light mb-3" style="max-width: 18rem;">
  <h4 class="card-header" style="font-family: 'Permanent Marker', cursive;"><%=link_to country.name, country, class: "text-secondary"%></h4>
  <div class="card-body">
    <h5 class="card-title">Currency: </h5>
    <p class="card-text"><%=country.currency %><p>
    </div>
    </div>
    &nbsp&nbsp&nbsp&nbsp&nbsp
    </div>
    <%end%>
    <%end%>
</div>

<br>
<br>

<h2 class="text-center" style="font-family: 'Permanent Marker', cursive;"> Posts </h2>
&nbsp&nbsp
<div class="card-deck justify-content-md-center">
<%current_user.posts.each do |post|%>
      <div class="row">
      <div class="card bg-light mb-3" style="max-width: 18rem;">
            <h4 class="card-header" style="font-family: 'Permanent Marker', cursive;"><%= link_to post.title.titleize, post_path(post), class: "text-secondary"%></h4>
            <div class="card-body">
            <p class="card-text"><%=post.title%></p>
            <p class="card-text"><%=post.content%></p>
            </div>
      </div>
      &nbsp&nbsp&nbsp&nbsp&nbsp
      </div>
<% end %>
</div>