config/routes.rb
Rails.application.routes.draw do
  resources :likes
  resources :posts do 
    resources :likes
  end
  # get "/posts/newsfeed", to: "post#newsfeed", as: "/newsfeed"
  # post "posts/new", to: "post#newsfeed"
  resources :activities
  resources :trips
  resources :countries
  resources :flights
  resources :users
  get "/login", to: "sessions#new"
  post "/login", to: "sessions#create"
  get "/logout", to: "sessions#logout"
  get '/home', to: "welcome#index", as: :home
  root :to => "welcome#index"
  
  

end

app/models/country.rb
class Country < ApplicationRecord
    has_many :flights
    has_many :trips, through: :flights
    has_many :users, through: :trips
end

app/controllers/countries_controller.rb
class CountriesController < ApplicationController
    before_action :find_country, only: [:show]
  

    def index
      @countries = Country.all.order('name ASC')
    end

    def show
    end

    private

    def country_params
        params.require(:country).permit(:name, :currency)
    end

    def find_country
        @country = Country.find_by(params[:id])
    end
end

app/helpers/countries_helper.rb
module CountriesHelper
end

app/views/countries/_form.html.erb
<%= form_for :country do |f| %>
 <%= f.label :name %>
 <%= f.text_field :name %>
 <%= f.label :currency %>
 <%= f.text_field :currency %>
 <%= f.submit %>
<%= end %>

app/views/countries/index.html.erb
<h1> Lists of Countries </h1>

<ul>
 <% @countries.each do |country| %>
   <li><%= link_to country.name, country_path(country) %></li>
   <% end %>
</ul>

app/views/countries/show.html.erb
<h1><%= @country.name %></h1>
<h3><%= @country.currency %></h3>