config/routes.rb
Rails.application.routes.draw do
  resources :likes
  resources :posts do 
    resources :likes
  end
  # get "/posts/newsfeed", to: "post#newsfeed", as: "/newsfeed"
  # post "posts/new", to: "post#newsfeed"
  resources :activities
  resources :trips
  resources :countries
  resources :flights
  resources :users
  get "/login", to: "sessions#new"
  post "/login", to: "sessions#create"
  get "/logout", to: "sessions#logout"
  get '/home', to: "welcome#index", as: :home
  root :to => "welcome#index"
  
  

end

app/models/post.rb
class Post < ApplicationRecord
    belongs_to :user
    has_many :likes, dependent: :destroy
    validates :title, presence: true
    validates :content, presence: true, length: {maximum: 150}

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
    before_action :authorized, except: [:index, :show]

    def index
        @posts = Post.all
    end
    # def newsfeed
    #     @posts = Post.all
    # end
    def show
        @post = Post.find(params[:id])
    end
    def new
        @user = current_user
        @post = Post.new
    end
    def create
        @post = Post.new(post_params)
        if @post.valid?
            @post.save
            redirect_to post_path(@post)
        else 
            render :new
        end
    end
    def edit 
        @post = Post.find(params[:id])
    end
    def update
        @post = Post.find(params[:id])
        @post.update(post_params)
        if @post.valid?
            @post.save
            
            redirect_to @post
        else 
            render :edit
        end
    end
    def destroy
        @post = post.destroy(params[:id])
        redirect_to home_path
      end
      private
      def post_params
        params.require(:post).permit(:title, :content, :user_id)
      end
      def find_post
        @post = Post.find(params[:id])
      end

end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_posts_form.html.erb
<% if @post.errors.any? %>
    <ul>
    <% @post.errors.full_messages.each do |e| %>
        <li class="error"><%= e %></li>
    <% end %>
    </ul>
<% end %>





<div class="container">
<%= form_for @post do |f| %>
 <div class="form-group">
 <%= f.label :title, class: "form-text"%><br>
 <%= f.text_field :title, class:"form-control", placeholder: "title" %>
 </div>
 <div class="form-group">
 <%= f.label :content, class: "form-text"%><br>
 <%= f.text_field :content, class:"form-control", placeholder: "content" %>
 </div>
 <div class="form-group">
 <%= f.hidden_field :user_id, :value => current_user.id %>
 </div>
   <%= token_tag %> 
 <%= f.submit "Submit", class: "btn btn-primary" %>
 </div>
<%end %>

app/views/posts/edit.html.erb
<h1> Edit Post <h/h1>

<%= render partial: 'posts_form', locals: {:post => @post} %>

app/views/posts/index.html.erb
<h1 style="text-align: center; font-family: 'Permanent Marker', cursive;" > All Posts </h1>

<div class="card-deck">
<div class="card-columns">

          <% @posts.each do |post| %>
        <div class="card ml-5" style="width: 18rem;">
            <div class="card border-dark mr-3 mb-0 mt-0 ml-0 " style="max-width: 18rem;">
                <div class="card-header text-grey link-grey bg-transparent border-dark" style="font-family: 'Permanent Marker', cursive;"><%=link_to "#{post.title.titleize}".html_safe, post_path(post), class: "text-secondary"%></div>
                <div class="card-subheader text-dark bg-transparent border-dark ml-2" style="font-family: 'Permanent Marker', cursive;" >By: <%= link_to post.user.name.titleize, user_path(post.user.id), class: "text-dark" %></div>       <div class="card-body text-dark">
                <p class="card-text"><%= post.content %></p>
                </div>
                    <div class="card-footer bg-transparent border-dark"><% pre_like = post.likes.find { |like| like.user_id == current_user.id} %>
                        <% if pre_like %>
                        <%= link_to ' ', post_like_path(post, pre_like), method: :delete, class: "fas fa-heart"  %>
                        <% else %>
                        <%= link_to ' ', post_likes_path(post.id), method: :post, class: "far fa-heart"%>&nbsp&nbsp&nbsp&nbsp
                        <% end %>
                        &nbsp&nbsp&nbsp&nbsp   Likes: <%=post.likes.count%>
                    </div>
            </div>
        </div>
       
         <% end %>
</div>
</div>

app/views/posts/new.html.erb
<h1> Create a New Post </h1>

<%= render partial: 'posts_form', locals: {:post => @post} %>

app/views/posts/newfeed.html.erb
<h1 class="text-center"><u><%= @user.name %>'s Posts </u></h1>

<ul>
<% @posts.each do |post| %>
    <li><%= link_to post.title, post %></li>
    <% end %>
</ul>

app/views/posts/show.html.erb
<div class="card" style="width: 80rem;">
<div class="card-body">
<h1 style="font-family: 'Permanent Marker', cursive;"><%= @post.title.titleize %></h1>
<h3> By: <%= link_to @post.user.name.titleize, user_path(@post.user.id) %></h3>
        <p class="card-text"><%= @post.content %></p>
        <% pre_like = @post.likes.find { |like| like.user_id == current_user.id} %>
        <% if pre_like %>
        <%= link_to ' ', post_like_path(@post, pre_like), method: :delete, class: "fas fa-heart" %> 
        <% else %>
         <%= link_to ' ', post_likes_path(@post), method: :post, class: "far fa-heart"%> 
          <button class="text-dark"><%= link_to "Edit Post", edit_post_path, class: "text-dark"%></button>
        <% end %>
    </div>
</div>




<br>
<br>
<br>
<br>
<br>
<br>

<button><%=link_to 'Back to all posts', posts_path %></button>